//EXPEDITION
export const REQUEST_ADD_NEW_EXPEDITION = "REQUEST_ADD_NEW_EXPEDITION";
export const REQUEST_GET_ALL_EXPEDITIONS = "REQUEST_GET_ALL_EXPEDITIONS";
export const REQUEST_UPDATE_EXPEDITION = "REQUEST_UPDATE_EXPEDITION";
export const REQUEST_GET_BY_ID_EXPEDITION = "REQUEST_GET_BY_ID_EXPEDITION";
export const REQUEST_DELETE_EXPEDITION = "REQUEST_DELETE_EXPEDITION";

//ROUTE
export const REQUEST_ADD_NEW_ROUTE = "REQUEST_ADD_NEW_ROUTE";
export const REQUEST_GET_ALL_ROUTE = "REQUEST_GET_ALL_ROUTE";
export const REQUEST_UPDATE_ROUTE = "REQUEST_UPDATE_ROUTE";
export const REQUEST_GET_BY_ID_ROUTE = "REQUEST_GET_BY_ID_ROUTE";
export const REQUEST_DELETE_ROUTE = "REQUEST_DELETE_ROUTE";

//TICKET
export const REQUEST_SELL_TICKET = "REQUEST_ADD_NEW_TICKET";
export const REQUEST_GET_ALL_TICKET = "REQUEST_GET_ALL_TICKET";
export const REQUEST_UPDATE_TICKET = "REQUEST_UPDATE_TICKET";
export const REQUEST_GET_BY_ID_TICKET = "REQUEST_GET_BY_ID_TICKET";
export const REQUEST_CANCEL_TICKET = "REQUEST_CANCEL_TICKET";
export const REQUEST_GET_PRICE_OF_TICKET = "REQUEST_GET_PRICE_OF_TICKET";

//BUS
export const REQUEST_ADD_NEW_BUS = "REQUEST_ADD_NEW_BUS";
export const REQUEST_GET_ALL_BUS = "REQUEST_GET_ALL_BUS";
export const REQUEST_UPDATE_BUS = "REQUEST_UPDATE_BUS";
export const REQUEST_GET_BY_ID_BUS = "REQUEST_GET_BY_ID_BUS";
export const REQUEST_DELETE_BUS = "REQUEST_DELETE_BUS";

//DRIVER
export const REQUEST_ADD_NEW_DRIVER = "REQUEST_ADD_NEW_DRIVER";
export const REQUEST_GET_ALL_DRIVER = "REQUEST_GET_ALL_DRIVER";
export const REQUEST_UPDATE_DRIVER = "REQUEST_UPDATE_DRIVER";
export const REQUEST_GET_BY_ID_DRIVER = "REQUEST_GET_BY_ID_DRIVER";
export const REQUEST_DELETE_DRIVER = "REQUEST_DELETE_DRIVER";

//HOST
export const REQUEST_ADD_NEW_HOST = "REQUEST_ADD_NEW_HOST";
export const REQUEST_GET_ALL_HOST = "REQUEST_GET_ALL_HOST";
export const REQUEST_UPDATE_HOST = "REQUEST_UPDATE_HOST";
export const REQUEST_GET_BY_ID_HOST = "REQUEST_GET_BY_ID_HOST";
export const REQUEST_DELETE_HOST = "REQUEST_DELETE_HOST";

//PASSENGER
export const REQUEST_ADD_NEW_PASSENGER = "REQUEST_ADD_NEW_PASSENGER";
export const REQUEST_GET_ALL_PASSENGER = "REQUEST_GET_ALL_PASSENGER";
export const REQUEST_UPDATE_PASSENGER = "REQUEST_UPDATE_PASSENGER";
export const REQUEST_GET_BY_ID_PASSENGER = "REQUEST_GET_BY_ID_PASSENGER";
export const REQUEST_DELETE_PASSENGER = "REQUEST_DELETE_PASSENGER";
